// ============ Website Builder · data ============
const { useState, useEffect, useRef, useMemo } = React;

// headline typefaces the customer can swap (body fonts stay per-template)
window.WEB_FONTS = {
  serif:   { name: "Instrument Serif", stack: "'Instrument Serif', Georgia, serif",  note: "editorial" },
  archivo: { name: "Archivo",          stack: "'Archivo', sans-serif",               note: "loud grotesque" },
  grotesk: { name: "Space Grotesk",    stack: "'Space Grotesk', sans-serif",         note: "techy" },
  news:    { name: "Newsreader",       stack: "'Newsreader', Georgia, serif",        note: "literary" },
  inter:   { name: "Inter",            stack: "'Inter', sans-serif",                 note: "neutral" },
};

window.WEB_ACCENTS = ["#c8a97e", "#2B3BFF", "#e6532f", "#00a86b", "#7c5cff", "#111111"];

window.WEB_TEMPLATES = {
  minimal: {
    name: "Atelier",
    tagline: "Portfolio / studio · airy, editorial, serif",
    vibe: "Light · editorial",
    accent: "#9a6b3f",
    font: "serif",
    sections: ["Nav", "Hero", "Selected work", "About + stats", "Contact CTA", "Footer"],
    fields: {
      brand: "Atelier Mira",
      navA: "Work", navB: "About", navC: "Contact",
      navCta: "Get in touch",
      kicker: "Design studio — est. 2021",
      heroA: "Considered design,",
      heroB: "quietly bold.",
      heroSub: "We craft identities, websites and print for small businesses that want to look like they mean it.",
      btnA: "See the work",
      btnB: "About the studio",
      workTitle: "Selected work",
      w1t: "Lumen Café", w1c: "Branding · 2026",
      w2t: "Habi Textiles", w2c: "Web · Identity",
      w3t: "Field Notes", w3c: "Editorial · Print",
      aboutTitle: "A small studio with sharp focus.",
      aboutBody: "Two designers, one developer, zero templates. Every project starts with a conversation and ends with something we are proud to sign.",
      s1n: "24", s1l: "Projects shipped",
      s2n: "09", s2l: "Industries",
      s3n: "5★", s3l: "Client rating",
      ctaTitle: "Have a project in mind?",
      ctaLink: "hello@ateliermira.ph",
      foot: "© 2026 Atelier Mira — All rights reserved.",
    },
  },
  bold: {
    name: "Loudhouse",
    tagline: "Agency / creative · dark, massive type",
    vibe: "Dark · loud",
    accent: "#e6532f",
    font: "archivo",
    sections: ["Nav", "Hero", "Marquee", "Services", "Showcase tiles", "Big CTA", "Footer"],
    fields: {
      brand: "STMP®",
      navA: "Work", navB: "Studio", navC: "Contact",
      heroA: "WE MAKE",
      heroX: "LOUD",
      heroB: "BRANDS.",
      heroSub: "A creative studio for businesses that refuse to be wallpaper. Strategy, identity and websites with actual volume.",
      marquee: "BRANDING — WEBSITES — MOTION — CAMPAIGNS — CONTENT —",
      s1t: "Brand identity", s1d: "Logos, systems, voice. The whole personality, engineered.",
      s2t: "Web design & build", s2d: "Fast, weird-in-a-good-way websites that convert.",
      s3t: "Motion & content", s3d: "Scroll-stopping video, social kits, launch assets.",
      ctaTitle: "GOT A PROJECT?",
      ctaBtn: "Start a project",
      ctaMail: "hey@stmp.studio",
      foot: "STMP® studio — Manila / remote",
    },
  },
  consult: {
    name: "Northpeak",
    tagline: "Consultancy / corporate · clean, trustworthy",
    vibe: "Light · corporate",
    accent: "#2B3BFF",
    font: "grotesk",
    sections: ["Nav", "Hero + stat cards", "Trust strip", "Services", "Testimonial", "Footer"],
    fields: {
      brand: "Northpeak Advisory",
      navA: "Services", navB: "About", navC: "Insights",
      navCta: "Book a consultation",
      kicker: "Business consultancy",
      heroTitle: "Clarity for growing businesses.",
      heroSub: "We help owner-led companies fix operations, plan finances and grow on purpose — not by accident.",
      btnA: "Book a consultation",
      btnB: "Our services",
      card1n: "+38%", card1l: "Avg. revenue growth",
      card2n: "120+", card2l: "Engagements completed",
      trust: "Trusted by 40+ local businesses",
      servTitle: "What we do",
      s1t: "Operations audit", s1d: "Find the friction. We map your processes and remove what slows you down.",
      s2t: "Financial planning", s2d: "Cashflow, pricing and forecasts you can actually act on.",
      s3t: "Growth strategy", s3d: "A 12-month plan with owners, deadlines and numbers attached.",
      quote: "“Northpeak found ₱2M in leaks we didn't know we had. Six months later we run leaner and earn more.”",
      quoteBy: "Alyssa Ramos — CEO, Ramos Logistics",
      foot: "© 2026 Northpeak Advisory · Legazpi City",
    },
  },
  folio: {
    name: "Devfolio",
    tagline: "Developer portfolio · dark, technical",
    vibe: "Dark · technical",
    accent: "#00c97a",
    font: "grotesk",
    sections: ["Nav", "Hero", "Selected projects", "Stack", "Experience", "Contact CTA", "Footer"],
    fields: {
      brand: "migs.dev",
      navA: "Projects", navB: "Stack", navC: "Contact",
      kicker: "Full-stack developer — Bicol, PH",
      heroA: "Hi, I'm Migs.",
      heroB: "I build fast, clean web apps.",
      heroSub: "Four years shipping React, Node and Supabase products for startups and small businesses. Currently open for freelance and full-time work.",
      btnA: "View projects",
      btnB: "Download CV",
      projTitle: "Selected projects",
      p1t: "Penny — profit tracker", p1d: "AI-powered sales and profit tracking for sari-sari stores.", p1g: "React Native · Supabase",
      p2t: "E-Suyo — transit maps", p2d: "Interactive commute map with a live jeepney fare calculator.", p2g: "Leaflet · Node",
      p3t: "Kape POS", p3d: "Configurable point-of-sale builder for cafés and food stalls.", p3g: "React · PostgreSQL",
      skillsTitle: "Stack",
      skills: "TypeScript · React · Node.js · Supabase · PostgreSQL · Tailwind · Figma",
      expTitle: "Experience",
      e1r: "Freelance developer", e1c: "Self-employed", e1d: "2023 — now",
      e2r: "Web dev intern", e2c: "LGU Legazpi", e2d: "2022",
      ctaTitle: "Let's build something.",
      ctaLink: "migs@hey.com",
      foot: "© 2026 migs.dev — built with too much coffee",
    },
  },
  resume: {
    name: "Curriculum",
    tagline: "Resume / CV · classic paper, print-ready",
    vibe: "Light · print-ready",
    accent: "#274690",
    font: "news",
    sections: ["Header", "Profile", "Experience", "Skills", "Education", "Links"],
    fields: {
      name: "Andrea Villanueva",
      role: "Marketing Manager",
      contactLine: "Legazpi City · andrea@mail.com · +63 917 000 0000",
      summaryTitle: "Profile",
      summary: "Marketing professional with 7 years building brands for food and retail businesses. Strong in campaigns, community and content that actually converts.",
      expTitle: "Experience",
      e1r: "Marketing Manager", e1c: "Bicol Coffee Co.", e1d: "2022 — Present", e1b: "Grew online sales 3× through seasonal campaigns and community programs.",
      e2r: "Brand Officer", e2c: "Mango & Co.", e2d: "2019 — 2022", e2b: "Led a full rebrand rolled out across 12 retail locations.",
      e3r: "Marketing Associate", e3c: "Vertex Media", e3d: "2017 — 2019", e3b: "Managed social channels and grew combined following to 80k.",
      skillsTitle: "Skills",
      sk1: "Brand strategy", sk2: "Social & content", sk3: "Paid ads", sk4: "Copywriting", sk5: "Analytics",
      eduTitle: "Education",
      edu1: "BS Business Administration",
      edu1s: "Bicol University · 2013 — 2017",
      refTitle: "Links",
      ref1: "linkedin.com/in/andreav",
      ref2: "andreav.com",
      foot: "References available on request.",
    },
  },
  tokyo: {
    name: "Akihiko",
    tagline: "Art director portfolio · monochrome, Tokyo editorial",
    vibe: "Dark · fashion",
    accent: "#f2f2f2",
    font: "inter",
    sections: ["Nav", "Hero + photo", "Giant wordmark", "Meta strip", "Portrait + statement", "Marquee", "City tiles", "Footer"],
    fields: {
      brand: "Palmer®",
      navLinks: "Home, Gallery, Work, Contact",
      basedIn: "Based in Tokyo 東京",
      roleTop: "Art Director + Framer Developer",
      heroTitle: "Pattern dimensions and moments that connect and leave a bold イメージ.",
      wordmark: "Akihiko",
      metaA: "Curated interfaces ビジュアル",
      metaB: "(WDX — 02)",
      metaC: "Digital designer",
      bioTitle: "13+ years™ of digital form, sharp interactions, and relentless creative discipline and effort.",
      bioCta: "Contact",
      marquee: "DIGITAL NOMAD — CREATIVE DEVELOPER — ART DIRECTION — TOKYO —",
      c1: "Cairo", c2: "oslo.", c3: "東京", c4: "Manila", c5: "Ghent",
      footA: "Akihiko Projects プロジェクト",
      footB: "(WDX — 10)",
      footC: "Creative design company",
    },
  },
};

window.WEB_TEMPLATE_ORDER = ["minimal", "bold", "consult", "folio", "resume", "tokyo"];

window.WEB_DEFAULT_CFG = { template: null, accent: null, font: null, content: {}, rev: 0 };

// resolve cfg → template meta + effective accent/font + merged text content
window.resolveWeb = (cfg) => {
  const t = window.WEB_TEMPLATES[cfg.template] || window.WEB_TEMPLATES.minimal;
  const fontKey = cfg.font || t.font;
  return {
    t,
    key: cfg.template || "minimal",
    accent: cfg.accent || t.accent,
    fontKey,
    font: window.WEB_FONTS[fontKey] || window.WEB_FONTS.serif,
    data: { ...t.fields, ...((cfg.content || {})[cfg.template] || {}) },
  };
};
